WPH11_TAXONOMY = {
    "Mechanics": [
        "SI units and quantities",
        "Scalars and vectors",
        "Displacement",
        "Velocity",
        "Acceleration",
        "Motion graphs",
        "Equations of motion",
        "Projectile motion",
        "Forces",
        "Newton's laws",
        "Free-body diagrams",
        "Weight and gravitational field strength",
        "Drag and terminal velocity",
        "Momentum",
        "Conservation of momentum",
        "Impulse",
        "Moments",
        "Equilibrium",
        "Work",
        "Energy",
        "Conservation of energy",
        "Power",
        "Efficiency",
    ],

    "Materials": [
        "Density",
        "Upthrust",
        "Viscosity",
        "Stokes' law",
        "Hooke's law",
        "Force-extension graphs",
        "Elastic and plastic deformation",
        "Stress",
        "Strain",
        "Young modulus",
        "Stress-strain graphs",
        "Elastic strain energy",
    ],

    "Experimental skills": [
        "Measurements",
        "Uncertainties",
        "Percentage uncertainty",
        "Graphs",
        "Gradient and intercept",
        "Experimental design",
        "Evaluation of experimental methods",
    ],
}


WPH12_TAXONOMY = {
    "Waves": [
        "Wave properties",
        "Transverse and longitudinal waves",
        "Wave speed",
        "Frequency and wavelength",
        "Phase difference",
        "Superposition",
        "Interference",
        "Coherence",
        "Path difference",
        "Diffraction",
        "Diffraction gratings",
        "Refraction",
        "Refractive index",
        "Total internal reflection",
        "Critical angle",
        "Polarisation",
        "Stationary waves",
        "Nodes and antinodes",
        "Harmonics",
    ],

    "Electricity": [
        "Electric current",
        "Charge",
        "Potential difference",
        "Resistance",
        "Ohm's law",
        "I-V characteristics",
        "Resistivity",
        "Electrical power",
        "Electrical energy",
        "Series circuits",
        "Parallel circuits",
        "Kirchhoff's laws",
        "Potential dividers",
        "EMF",
        "Internal resistance",
    ],

    "Experimental skills": [
        "Measurements",
        "Uncertainties",
        "Percentage uncertainty",
        "Graphs",
        "Gradient and intercept",
        "Experimental design",
        "Evaluation of experimental methods",
    ],
}


TAXONOMIES = {
    "WPH11": WPH11_TAXONOMY,
    "WPH12": WPH12_TAXONOMY,
}